### ISSUE TITLE
[MINOR] Is this still being worked on?

### ISSUE THREAD

**Issue by steelshot** [CelesTek-Team/HexCraft#16]
Simple question, is this still being worked on? 

Really wouldn't like to see this awesome work go. Most likely going to try learning some MC coding and attempt to maintain this at least for myself then.

**Comment by CelesTek-Team** [comment]
Hey!

The only reason this project is on pause is due to tons of other projects and college. We will return to this soon and probably update it for 1.10 as well. We are terribly sorry that it is on hold, even we still play with it on 1.7.10... We have tons of features planned, but won't be saying anything yet!

**Comment by steelshot** [comment]
No need to apologize, life is more important than some mod for a game. Glad to see that its not abandoned :)
